// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ChamaGroup$Type } from "./ChamaGroup";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ChamaGroup"]: ChamaGroup$Type;
    ["contracts/ChamaGroup.sol:ChamaGroup"]: ChamaGroup$Type;
  }

  interface ContractTypesMap {
    ["ChamaGroup"]: GetContractReturnType<ChamaGroup$Type["abi"]>;
    ["contracts/ChamaGroup.sol:ChamaGroup"]: GetContractReturnType<ChamaGroup$Type["abi"]>;
  }
}
