// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ChamaStructs$Type } from "./ChamaStructs";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ChamaStructs"]: ChamaStructs$Type;
    ["contracts/ChamaStructs.sol:ChamaStructs"]: ChamaStructs$Type;
  }

  interface ContractTypesMap {
    ["ChamaStructs"]: GetContractReturnType<ChamaStructs$Type["abi"]>;
    ["contracts/ChamaStructs.sol:ChamaStructs"]: GetContractReturnType<ChamaStructs$Type["abi"]>;
  }
}
