// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface ChamaStructs$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "ChamaStructs",
  "sourceName": "contracts/ChamaStructs.sol",
  "abi": [],
  "bytecode": "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea264697066735822122049258c1c6f6f0b9c2afa9bedc216b3d400ef23497bbb71e01ab1e349dbd4cb1664736f6c634300081c0033",
  "deployedBytecode": "0x600080fdfea264697066735822122049258c1c6f6f0b9c2afa9bedc216b3d400ef23497bbb71e01ab1e349dbd4cb1664736f6c634300081c0033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "ChamaStructs",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ChamaStructs$Type["abi"]>>;
  export function deployContract(
    contractName: "contracts/ChamaStructs.sol:ChamaStructs",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<ChamaStructs$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "ChamaStructs",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ChamaStructs$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "contracts/ChamaStructs.sol:ChamaStructs",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<ChamaStructs$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "ChamaStructs",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ChamaStructs$Type["abi"]>>;
  export function getContractAt(
    contractName: "contracts/ChamaStructs.sol:ChamaStructs",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<ChamaStructs$Type["abi"]>>;
}
