// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { ChamaFactory$Type } from "./ChamaFactory";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["ChamaFactory"]: ChamaFactory$Type;
    ["contracts/ChamaFactory.sol:ChamaFactory"]: ChamaFactory$Type;
  }

  interface ContractTypesMap {
    ["ChamaFactory"]: GetContractReturnType<ChamaFactory$Type["abi"]>;
    ["contracts/ChamaFactory.sol:ChamaFactory"]: GetContractReturnType<ChamaFactory$Type["abi"]>;
  }
}
